### ISSUE TITLE
Редактирование и удаление записей

### ISSUE THREAD

**Issue by Ampa1R** [JokerCerg/taskchecker-project#4]
На детальную страницу записи нужно добавить две кнопки: 
- Редактировать - переходит на страницу с редактированием записи
- Удалить - открывает [модальное окно](https://getbootstrap.com/docs/4.3/components/modal/) для подтверждение удаления записи

**Comment by JokerCerg** [comment]
Прими работу

**Comment by JokerCerg** [comment]
прими работу)
